### PR TITLE
Generating project with CMake

### PR DESCRIPTION
**Pull request by cjlcarvalho**

### CODE REVIEW

**Comment by antonioborondo** [comment]
@cjlcarvalho Thank you very much for your PR! 😃

I am not able to build the project with your changes. I get so many compilation errors in my environment. However, applying a few changes on the top of yours, I was able to build it!

You can find the new branch with all the changes here (work in progress): https://github.com/antonioborondo/pdf_reader/tree/cmake

**Comment by cjlcarvalho** [comment]
@antonioborondo Is there any other issue with this CMake build?

**Comment by antonioborondo** [comment]
@cjlcarvalho Are you actually able to build the project with this CMake build?

**Comment by antonioborondo** [comment]
Project is now generated with CMake. Thanks for your help!

**Pull request closed without merging**
